resolver: lts-10.7

packages:
- lndr-backend/
- lndr-cli/
- location:
    git: git@github.com:aupiff/hs-web3.git
    commit: fcb6fcf23fc673cade5f8d0be41f024b2d40ad7b
  extra-dep: true
- location:
    git: git@github.com:aupiff/ethereumhs-util.git
    commit: 0a187b13db9199dfb92e2124c9b4ca2ebf2c6549
  extra-dep: true

extra-deps:
- secp256k1-0.5.2
- dhall-1.8.0
