resolver: lts-9.12

packages:
- lndr-backend/
- lndr-cli/
- location:
    git: git@github.com:airalab/hs-web3.git
    commit: fd22da4a178c9e8f570c3d4b8f0ce589fa40e207
  extra-dep: true
- location:
    git: git@github.com:aupiff/ethereumhs-util.git
    commit: a6a563846a0896a92953df64b9128586e769a2cd
  extra-dep: true

extra-deps:
- secp256k1-0.5.2
- dhall-1.8.0
