defaults: &defaults
  working_directory: ~
  docker:
  - image: blockmason/lndr-circleci:1.0.0.0

version: 2
jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        keys:
        - v2-{{ checksum "stack.yaml" }}
    - run:
        name: stack setup
        command: |
          stack setup
    - run:
        name: stack install
        command: |
          stack install
    - save_cache:
        key: v2-{{ checksum "stack.yaml" }}
        paths:
        - ~/.ghc
        - ~/.cabal
        - ~/.stack
    - run:
        name: Prepare artifacts
        command: |
          mkdir artifacts
          cp \
            "${HOME}/.local/bin/lndr-server" \
            Dockerfile \
            .dockerignore \
            $(perl -n -e'/^!\/(.+)/ && print "$1\n"' < .dockerignore | xargs) \
            artifacts/
    - store_artifacts:
        path: artifacts
