defaults: &defaults
  working_directory: ~
  docker:
  - image: blockmason/lndr-circleci:1.0.0.0

version: 2
jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        keys:
        - v2-{{ checksum "stack.yaml" }}
    - run:
        name: stack setup
        command: |
          stack setup
    - run:
        name: stack install
        command: |
          stack install
    - save_cache:
        key: v2-{{ checksum "stack.yaml" }}
        paths:
        - ~/.ghc
        - ~/.cabal
        - ~/.stack
    - run:
        name: Prepare artifacts
        command: |
          mkdir artifacts
          for artifact in lndr lndr-server; do
            cp "${HOME}/.local/bin/${artifact}" artifacts/
          done
    - store_artifacts:
        path: artifacts
